# Generated by Django 3.2.25 on 2024-06-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_cartegory_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='was',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
